# Generated by Django 3.1 on 2020-10-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tital',
            new_name='title',
        ),
    ]
